**question 1**

In [1]:
import numpy as np

In [15]:
#part 1.a
Px = 3
Py = 5
teta = 0.7*np.pi
omega = 0.2#rad/sec
state_vector = np.matrix(([3],[5],[0.7*np.pi],[0.2]))

In [22]:
def move_equations(Px,Py,teta,omega):
    v = 10
    delta_t = 0.2
    Px_next = Px + (v/teta)*(np.sin(teta + (delta_t*teta)))-np.sin(teta)
    Py_next = Py + (v/teta)*(np.cos(teta) - np.cos(teta + (delta_t * teta)))
    Teta_new = teta + (0.2*teta)
    new_vector = np.matrix([Px_next,Py_next,Teta_new]).transpose()
    return new_vector

In [23]:
print(move_equations(Px,Py,teta,omega))

[[4.38165382]
 [6.3119889 ]
 [2.63893783]]


**question 2**

In [24]:
#part 1.b
print(move_equations(Px,Py,teta,0))

[[4.38165382]
 [6.3119889 ]
 [2.63893783]]


In [119]:
def gloabal_coordinations(obs, Xp, Yp, teta):
    F_matrix = np.matrix(([round(np.cos(teta),2) , round(-1.0*np.sin(teta),2) , Xp] , [ round(np.sin(teta),2) ,round(np.cos(teta),2) , Yp] ,[ 0.0,0.0,1.0]))
    observe_vector = np.matrix([obs[0],obs[1],1]).transpose()
    return F_matrix * observe_vector
def orientation_coordinations(landmark,Xp,Yp,teta):
    global_matrix = np.matrix([landmark[0],landmark[1],1]).transpose()
    inverseFmatrix = np.matrix(([round(np.cos(teta),2) , round(-1.0*np.sin(teta),2) , Xp] , [ round(np.sin(teta),2) ,round(np.cos(teta),2) , Yp] ,[ 0.0,0.0,1.0])).I
    return  inverseFmatrix * global_matrix 

In [120]:
#part 2 a
Xp =10.0
Yp = 21.0
teta = 30.0
radian_teta = teta * np.pi / 180

obs1 = (0,0)
obs2 = (18,32)
print(gloabal_coordinations(obs1,Xp,Yp,radian_teta))
print(gloabal_coordinations(obs2,Xp,Yp,radian_teta))

[[10.]
 [21.]
 [ 1.]]
[[ 9.66]
 [57.84]
 [ 1.  ]]


In [121]:
#part 2 b
landmark = (21,10)
orintation_voordinations(landmark,Xp,Yp,radian_teta)

matrix([[  4.04210944],
        [-14.96672957],
        [  1.        ]])

In [122]:
#part 2 c
orientation_coordinations(landmark,Xp,Yp,0)

matrix([[ 11.],
        [-11.],
        [  1.]])

**question 3*